"""Extract the receive-core conformance corpus from the current Python implementation.

This script is the M1 contract snapshot for the Rust receive-core migration. It
records public API shape, path canonicalization edge cases, deterministic BagIt
writer bytes, normalized receive-bag evidence, validation/mismatch behavior, and
CLI JSON/text behavior. The committed fixtures are intentionally generated from
the existing Python implementation before Rust code replaces it.
"""

from __future__ import annotations

import argparse
import contextlib
import dataclasses
import datetime as dt
import hashlib
import inspect
import io
import json
import os
import shutil
import tempfile
from collections.abc import Callable, Iterable, Iterator, Mapping
from pathlib import Path
from typing import Any

import sutradhara_receive
from sutradhara_receive import (
    BAG_PROFILE,
    CANONICALIZATION_VERSION,
    PACKAGE_GLOBS,
    PACKAGE_INDEX_NAME,
    PACKAGE_PROFILE_HASH,
    PACKAGE_PROFILE_VERSION,
    RECEIVE_PACKAGE,
    RECEIVE_VERSION,
    bag_info_metadata,
    member_name,
    read_bag_info,
    read_manifest_sha256,
    read_package_index,
    receive_source,
    validate_bag,
    write_bagit_files,
)
from sutradhara_receive import cli as receive_cli
from sutradhara_receive import core as receive_core
from sutradhara_receive.member_name import escape_member_name, unescape_member_name

FIXED_NOW = dt.datetime(2026, 6, 18, 12, 34, 56, tzinfo=dt.UTC)
DEFAULT_FIXTURE_ROOT = Path(__file__).resolve().parents[1] / "fixtures"

TEXT_BAG_FILES = {
    "bagit.txt",
    "bag-info.txt",
    "manifest-sha256.txt",
    "tagmanifest-sha256.txt",
    "package-index.json",
    "intake.json",
}


def build_corpus(work_root: Path) -> dict[str, Any]:
    """Return the complete current receive contract corpus."""

    work_root.mkdir(parents=True, exist_ok=True)
    return {
        "public_api": public_api_snapshot(),
        "strings": string_fixtures(work_root / "strings"),
        "writer_outputs": writer_output_fixtures(work_root / "writers"),
        "receive_bags": receive_bag_fixtures(work_root / "bags"),
        "validate_mismatch": validate_mismatch_fixtures(work_root / "validate"),
        "cli_matrix": cli_matrix_fixtures(work_root / "cli"),
    }


def write_corpus(corpus: Mapping[str, Any], fixture_root: Path = DEFAULT_FIXTURE_ROOT) -> None:
    """Write a generated corpus to the fixture directory."""

    fixture_root.mkdir(parents=True, exist_ok=True)
    (fixture_root / "README.md").write_text(
        "\n".join(
            [
                "# sutradhara-receive conformance fixtures",
                "",
                "Generated by `packages/sutradhara-receive/scripts/extract_fixtures.py`.",
                "These files snapshot the current Python receive contract before the",
                "Rust receive-core migration. Update them only by intentionally running",
                "the extractor after a reviewed contract change.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    for name, payload in corpus.items():
        _write_json(fixture_root / f"{name}.json", payload)


def load_committed_corpus(fixture_root: Path = DEFAULT_FIXTURE_ROOT) -> dict[str, Any]:
    """Load all committed JSON fixtures."""

    return {
        path.stem: json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(fixture_root.glob("*.json"))
    }


def public_api_snapshot() -> dict[str, Any]:
    """Describe the Python import surface the PyO3 wheel must preserve."""

    dataclass_shapes: dict[str, Any] = {}
    class_bases: dict[str, list[str]] = {}
    top_level_functions: dict[str, str] = {}
    top_level_constants: dict[str, Any] = {}
    for name in sutradhara_receive.__all__:
        value = getattr(sutradhara_receive, name)
        if inspect.isclass(value):
            class_bases[name] = [_qualified_name(base) for base in value.__bases__]
            if dataclasses.is_dataclass(value):
                dataclass_shapes[name] = _dataclass_shape(value)
            continue
        if callable(value):
            top_level_functions[name] = str(inspect.signature(value))
            continue
        top_level_constants[name] = _jsonable(value)

    return {
        "schema_version": 1,
        "module": "sutradhara_receive",
        "__all__": list(sutradhara_receive.__all__),
        "__all_count": len(sutradhara_receive.__all__),
        "constants": top_level_constants,
        "functions": top_level_functions,
        "classes": class_bases,
        "dataclasses": dataclass_shapes,
        "member_name_exports": _module_defined_exports(member_name),
        "member_name_signatures": _module_signatures(member_name),
        "cli_exports": _module_defined_exports(receive_cli),
        "cli_signatures": _module_signatures(receive_cli),
        "cli_json_schema": {
            "receive_required_keys": [
                "bag_info_path",
                "bag_profile",
                "file_count",
                "intake_dir",
                "intake_id",
                "manifest_path",
                "sentinel_path",
                "skipped_count",
                "tagmanifest_path",
                "total_bytes",
            ],
            "confirmation_keys": ["detail", "marker_path", "release_ok", "status"],
            "sweep_required_keys": ["removed"],
        },
    }


def string_fixtures(work_root: Path) -> dict[str, Any]:
    """Build escaping and canonicalization fixture vectors."""

    root = work_root / "root"
    root.mkdir(parents=True, exist_ok=True)
    escape_cases = [
        ("ascii", b"clip.mov"),
        ("utf8_nfc", "Caf\u00e9.mov".encode("utf-8")),
        ("utf8_nfd", b"Cafe\xcc\x81.mov"),
        ("backslash", b"dir\\name.mov"),
        ("control", b"line\nfeed\x7f.mov"),
        ("invalid_utf8", b"\xffbad\xc3(.mov"),
        ("unassigned_codepoint", "\u0378.txt".encode("utf-8")),
    ]
    canonical_fs_cases = [
        ("nfd_to_nfc", [b"Cafe\xcc\x81.mov"]),
        ("invalid_utf8", [b"\xff.bin"]),
        ("nested", [b"Folder", b"clip.mov"]),
        ("backslash", [b"we\\ird.mov"]),
        ("control", [b"a\nb.mov"]),
        ("unassigned_codepoint", ["\u0378.txt".encode("utf-8")]),
    ]
    manifest_cases = [
        "./data/Cafe\u0301.mov",
        "/data/clip.mov",
        r"data/\xff.bin",
        r"data/we\\ird.mov",
    ]
    manifest_rejections = ["", "..", "data/../x", r"data/bad\q"]
    return {
        "schema_version": 1,
        "escape_member_name": [
            {
                "name": name,
                "raw_hex": raw.hex(),
                "escaped": escape_member_name(raw),
                "roundtrip_hex": unescape_member_name(escape_member_name(raw)).hex(),
            }
            for name, raw in escape_cases
        ],
        "canonicalize_filesystem_path": [
            {
                "name": name,
                "components_hex": [component.hex() for component in components],
                "canonical": receive_core.canonicalize_filesystem_path(
                    _path_from_raw_components(root, components),
                    root,
                ),
            }
            for name, components in canonical_fs_cases
        ],
        "canonicalize_manifest_path": [
            {"raw": raw, "canonical": receive_core.canonicalize_manifest_path(raw)}
            for raw in manifest_cases
        ],
        "canonicalize_manifest_rejections": [
            {
                "raw": raw,
                "error": _raises_message(lambda raw=raw: receive_core.canonicalize_manifest_path(raw)),
            }
            for raw in manifest_rejections
        ],
    }


def writer_output_fixtures(work_root: Path) -> dict[str, Any]:
    """Build byte-for-byte fixtures for lower-level writers."""

    bag = work_root / "bag"
    data = bag / "data"
    data.mkdir(parents=True, exist_ok=True)
    payload = b"hello"
    digest = hashlib.sha256(payload).hexdigest()
    (data / "clip%.mov").write_bytes(payload)
    metadata = bag_info_metadata(
        intake_id="bag-001",
        source_kind="card",
        operator="op",
        source_ref="A001",
        artifactclass="camera-original",
        label="shoot",
        started_at=FIXED_NOW,
        file_count=1,
        total_bytes=len(payload),
        skipped_count=0,
    )
    result = write_bagit_files(bag, entries={"clip%.mov": digest}, metadata=metadata)

    package_source = work_root / "package-source"
    _write_package_fixture(package_source / "GOLDEN.fcpbundle")
    package_result = receive_source(
        package_source,
        landing=work_root / "package-landing",
        source_kind="card",
        operator="op",
        now=FIXED_NOW,
    )
    package_tar = package_result.intake_dir / "data" / "GOLDEN.fcpbundle.tar"
    package_index = read_package_index(package_result.intake_dir / PACKAGE_INDEX_NAME)
    return {
        "schema_version": 1,
        "constants": {
            "RECEIVE_VERSION": RECEIVE_VERSION,
            "RECEIVE_PACKAGE": RECEIVE_PACKAGE,
            "CANONICALIZATION_VERSION": CANONICALIZATION_VERSION,
            "PACKAGE_PROFILE_VERSION": PACKAGE_PROFILE_VERSION,
            "PACKAGE_PROFILE_HASH": PACKAGE_PROFILE_HASH,
            "PACKAGE_GLOBS": list(PACKAGE_GLOBS),
            "BAG_PROFILE": BAG_PROFILE,
        },
        "bagit_writer": {
            "bagit.txt": (bag / "bagit.txt").read_text(encoding="utf-8"),
            "manifest-sha256.txt": result.manifest_path.read_text(encoding="utf-8"),
            "bag-info.txt": result.bag_info_path.read_text(encoding="utf-8"),
            "tagmanifest-sha256.txt": result.tagmanifest_path.read_text(encoding="utf-8"),
        },
        "package_tar": {
            "path": "data/GOLDEN.fcpbundle.tar",
            "sha256": _sha256_file(package_tar),
            "size": package_tar.stat().st_size,
            "package_index": package_index,
        },
    }


def receive_bag_fixtures(work_root: Path) -> dict[str, Any]:
    """Build normalized complete-bag snapshots."""

    return {
        "schema_version": 1,
        "normalization_tokens": [
            "<FIXTURE-ROOT>",
            "<SOURCE>",
            "<LANDING>",
            "<INTAKE-ID>",
        ],
        "cases": [
            _receive_case(
                work_root,
                "mixed-files",
                lambda source: _write_mixed_source(source),
            ),
            _receive_case(
                work_root,
                "package-with-symlink",
                lambda source: _write_package_fixture(source / "A001.photoslibrary"),
            ),
        ],
    }


def validate_mismatch_fixtures(work_root: Path) -> dict[str, Any]:
    """Build validation and manifest mismatch behavior fixtures."""

    digest = hashlib.sha256(b"video").hexdigest()
    validation_cases = []

    missing = _simple_received_bag(work_root, "missing-payload")
    (missing / "data" / "clip.mov").unlink()
    validation_cases.append(_validation_snapshot("missing-payload", missing))

    corrupt = _simple_received_bag(work_root, "corrupt-payload")
    (corrupt / "data" / "clip.mov").write_bytes(b"corrupt")
    validation_cases.append(_validation_snapshot("corrupt-payload", corrupt))

    unsupported = _simple_received_bag(work_root, "unsupported-package")
    metadata = read_bag_info(unsupported / "bag-info.txt")
    metadata["Receive-Package"] = "sutradhara-receive/999.0.0"
    write_bagit_files(
        unsupported,
        entries=read_manifest_sha256(unsupported / "manifest-sha256.txt"),
        metadata=metadata,
    )
    validation_cases.append(_validation_snapshot("unsupported-package", unsupported))

    return {
        "schema_version": 1,
        "manifest_mismatch": [
            {
                "name": "nfc_equivalent",
                "actual": {"Caf\u00e9.mov": digest},
                "expected": {"Cafe\u0301.mov": digest},
                "result": receive_core.manifest_mismatch(
                    {"Caf\u00e9.mov": digest},
                    {"Cafe\u0301.mov": digest},
                ),
            },
            {
                "name": "extra",
                "actual": {"extra.mov": digest},
                "expected": {},
                "result": receive_core.manifest_mismatch({"extra.mov": digest}, {}),
            },
            {
                "name": "missing",
                "actual": {},
                "expected": {"missing.mov": digest},
                "result": receive_core.manifest_mismatch({}, {"missing.mov": digest}),
            },
            {
                "name": "mismatched",
                "actual": {"clip.mov": "0" * 64},
                "expected": {"clip.mov": digest},
                "result": receive_core.manifest_mismatch(
                    {"clip.mov": "0" * 64},
                    {"clip.mov": digest},
                ),
            },
        ],
        "validate_bag": validation_cases,
    }


def cli_matrix_fixtures(work_root: Path) -> dict[str, Any]:
    """Build CLI behavior fixtures with normalized paths and intake ids."""

    cases = [
        _cli_case(work_root, "bare-fake-source-json", "receive"),
        _cli_case(work_root, "explicit-run-json", "run"),
        _cli_case(work_root, "confirm-timeout-exit-3", "timeout"),
        _cli_case(work_root, "source-and-fake-source-usage", "usage"),
        _cli_case(work_root, "sweep-json", "sweep"),
        _cli_case(work_root, "sweep-orphans-json", "sweep-orphans"),
    ]
    return {
        "schema_version": 1,
        "cases": cases,
        "confirmation_rendering": _confirmation_rendering_cases(work_root),
    }


def _receive_case(
    work_root: Path,
    name: str,
    write_source: Callable[[Path], None],
) -> dict[str, Any]:
    source = work_root / "sources" / name
    landing = work_root / "landings" / name
    write_source(source)
    with _fixed_minted_intake_id(f"fixture-{name}"):
        result = receive_source(
            source,
            landing=landing,
            source_kind="card",
            operator="Op Name",
            source_ref="SRC",
            artifactclass="camera-original",
            label="fixture",
            now=FIXED_NOW,
        )
    return {
        "name": name,
        "result": _normalize_json(
            receive_cli.receive_result_payload(result, None),
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=result.intake_id,
        ),
        "validation": _validation_result_payload(validate_bag(result.intake_dir)),
        "files": _snapshot_bag_files(
            result.intake_dir,
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=result.intake_id,
        ),
    }


@contextlib.contextmanager
def _fixed_minted_intake_id(intake_id: str) -> Iterator[None]:
    original = receive_core._mint_intake_id
    receive_core._mint_intake_id = lambda _operator, _now, _landing_root: intake_id
    try:
        yield
    finally:
        receive_core._mint_intake_id = original


def _cli_case(work_root: Path, name: str, kind: str) -> dict[str, Any]:
    case_root = work_root / name
    source = case_root / "source"
    landing = case_root / "landing"
    if kind in {"receive", "run", "timeout", "usage"}:
        source.mkdir(parents=True, exist_ok=True)
        (source / "clip.mov").write_bytes(b"video")

    if kind == "receive":
        argv = [
            "--fake-source",
            str(source),
            "--landing",
            str(landing),
            "--source-kind",
            "card",
            "--operator",
            "Op",
            "--json",
        ]
    elif kind == "run":
        argv = [
            "run",
            "--fake-source",
            str(source),
            "--landing",
            str(landing),
            "--source-kind",
            "card",
            "--operator",
            "Op",
            "--json",
        ]
    elif kind == "timeout":
        argv = [
            "--fake-source",
            str(source),
            "--landing",
            str(landing),
            "--source-kind",
            "card",
            "--operator",
            "Op",
            "--confirm-timeout",
            "0",
            "--json",
        ]
    elif kind == "usage":
        fake = case_root / "fake"
        fake.mkdir(parents=True, exist_ok=True)
        argv = [
            str(source),
            "--fake-source",
            str(fake),
            "--landing",
            str(landing),
            "--source-kind",
            "card",
            "--operator",
            "Op",
        ]
    elif kind in {"sweep", "sweep-orphans"}:
        _write_sweep_fixture(landing)
        argv = [
            kind,
            "--landing",
            str(landing),
            "--older-than-hours",
            "24",
            "--json",
        ]
    else:
        raise AssertionError(kind)

    exit_code, stdout, stderr = _run_receive_cli(argv)
    stdout_payload = _json_or_none(stdout)
    intake_id = (
        str(stdout_payload["intake_id"])
        if isinstance(stdout_payload, dict) and "intake_id" in stdout_payload
        else None
    )
    return {
        "name": name,
        "argv": _normalize_json(
            argv,
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=intake_id,
        ),
        "exit_code": exit_code,
        "stdout": _normalize_text(
            stdout,
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=intake_id,
        ),
        "stderr": _normalize_text(
            stderr,
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=intake_id,
        ),
        "stdout_json": _normalize_json(
            stdout_payload,
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=intake_id,
        ),
    }


def _confirmation_rendering_cases(work_root: Path) -> list[dict[str, Any]]:
    result = receive_core.ReceiveResult(
        intake_id="fixture-intake",
        intake_dir=work_root / "landing" / "fixture-intake",
        manifest_path=work_root / "landing" / "fixture-intake" / "manifest-sha256.txt",
        bag_info_path=work_root / "landing" / "fixture-intake" / "bag-info.txt",
        tagmanifest_path=work_root / "landing" / "fixture-intake" / "tagmanifest-sha256.txt",
        sentinel_path=work_root / "landing" / "fixture-intake" / "intake.json",
        file_count=1,
        total_bytes=5,
        skipped_count=0,
        bag_profile=BAG_PROFILE,
    )
    confirmations = [
        receive_core.ConfirmationResult(True, "verified", work_root / "verified.json", {"ok": True}),
        receive_core.ConfirmationResult(False, "pending", work_root / "verified.json", None),
        receive_core.ConfirmationResult(
            False,
            "quarantined",
            work_root / "intake.quarantined.json",
            {"reason": "bag-invalid"},
        ),
        receive_core.ConfirmationResult(
            False,
            "discrepancy",
            work_root / "intake.discrepancy.json",
            {"details": {"missing": ["clip.mov"]}},
        ),
        receive_core.ConfirmationResult(False, "timeout", None, None),
    ]
    cases = []
    for confirmation in confirmations:
        stdout_lines, stderr_lines = receive_cli.receive_text_lines(result, confirmation)
        cases.append(
            {
                "status": confirmation.status,
                "payload": _normalize_json(
                    receive_cli.receive_result_payload(result, confirmation),
                    work_root=work_root,
                    source=None,
                    landing=work_root / "landing",
                    intake_id=result.intake_id,
                ),
                "stdout_lines": _normalize_json(
                    stdout_lines,
                    work_root=work_root,
                    source=None,
                    landing=work_root / "landing",
                    intake_id=result.intake_id,
                ),
                "stderr_lines": _normalize_json(
                    stderr_lines,
                    work_root=work_root,
                    source=None,
                    landing=work_root / "landing",
                    intake_id=result.intake_id,
                ),
                "exit_code": 0 if confirmation.release_ok else 3,
            }
        )
    return cases


def _snapshot_bag_files(
    intake_dir: Path,
    *,
    work_root: Path,
    source: Path,
    landing: Path,
    intake_id: str,
) -> list[dict[str, Any]]:
    records = []
    for path in sorted(item for item in intake_dir.rglob("*") if item.is_file()):
        relpath = path.relative_to(intake_dir).as_posix()
        if relpath == "receive.log":
            continue
        if relpath in TEXT_BAG_FILES:
            records.append(
                {
                    "path": relpath,
                    "kind": "text",
                    "text": _normalize_text(
                        path.read_text(encoding="utf-8"),
                        work_root=work_root,
                        source=source,
                        landing=landing,
                        intake_id=intake_id,
                    ),
                }
            )
        else:
            records.append(
                {
                    "path": relpath,
                    "kind": "bytes",
                    "sha256": _sha256_file(path),
                    "size": path.stat().st_size,
                }
            )
    return records


def _simple_received_bag(work_root: Path, name: str) -> Path:
    source = work_root / "sources" / name
    source.mkdir(parents=True, exist_ok=True)
    (source / "clip.mov").write_bytes(b"video")
    result = receive_source(
        source,
        landing=work_root / "landing" / name,
        source_kind="card",
        operator="op",
        now=FIXED_NOW,
    )
    return result.intake_dir


def _validation_snapshot(name: str, bag_root: Path) -> dict[str, Any]:
    validation = validate_bag(bag_root)
    return {
        "name": name,
        "complete": validation.complete,
        "valid": validation.valid,
        "missing": validation.missing,
        "extra": validation.extra,
        "mismatched": validation.mismatched,
        "tag_mismatched": validation.tag_mismatched,
        "errors": validation.errors,
        "details": validation.details(),
    }


def _validation_result_payload(validation: Any) -> dict[str, Any]:
    return {
        "complete": validation.complete,
        "valid": validation.valid,
        "missing": validation.missing,
        "extra": validation.extra,
        "mismatched": validation.mismatched,
        "tag_mismatched": validation.tag_mismatched,
        "errors": validation.errors,
        "details": validation.details(),
    }


def _write_mixed_source(source: Path) -> None:
    source.mkdir(parents=True, exist_ok=True)
    (source / "clip.mov").write_bytes(b"video")
    (source / "Cafe\u0301.mov").write_bytes(b"cafe")


def _write_package_fixture(package_root: Path) -> None:
    (package_root / "Render").mkdir(parents=True, exist_ok=True)
    (package_root / "Render" / "clip01.mov").write_bytes(b"clip-one")
    (package_root / "Render" / "clip02.mov").write_bytes(b"clip-two")
    _write_raw_named_file(package_root / "Render", b"\xfelegacy.dat", b"legacy")
    (package_root / "._meta").write_bytes(b"appledouble")
    (package_root / "library.plist").write_bytes(b"plist")
    link = package_root / "clip-link.mov"
    with contextlib.suppress(FileExistsError):
        link.symlink_to("Render/clip01.mov")


def _write_sweep_fixture(landing: Path) -> None:
    stale = landing / "stale"
    fresh = landing / "fresh"
    complete = landing / "complete"
    for path in (stale, fresh, complete):
        path.mkdir(parents=True, exist_ok=True)
        (path / ".receiving.json").write_text("{}", encoding="utf-8")
    (complete / "intake.json").write_text("{}", encoding="utf-8")
    old = dt.datetime.now().timestamp() - 48 * 3600
    os.utime(stale / ".receiving.json", (old, old))


def _run_receive_cli(argv: list[str]) -> tuple[int, str, str]:
    stdout = io.StringIO()
    stderr = io.StringIO()
    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        exit_code = receive_cli.main(argv)
    return exit_code, stdout.getvalue(), stderr.getvalue()


def _path_from_raw_components(root: Path, components: Iterable[bytes]) -> Path:
    path = root
    for component in components:
        path = path / os.fsdecode(component)
    return path


def _write_raw_named_file(parent: Path, raw_name: bytes, data: bytes) -> None:
    parent.mkdir(parents=True, exist_ok=True)
    raw_parent = os.fsencode(parent)
    raw_path = raw_parent + os.sep.encode() + raw_name
    fd = os.open(raw_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    try:
        os.write(fd, data)
    finally:
        os.close(fd)


def _normalize_text(
    text: str,
    *,
    work_root: Path,
    source: Path | None,
    landing: Path | None,
    intake_id: str | None,
) -> str:
    replacements = [(str(work_root), "<FIXTURE-ROOT>")]
    if source is not None:
        replacements.append((str(source), "<SOURCE>"))
    if landing is not None:
        replacements.append((str(landing), "<LANDING>"))
    if intake_id is not None:
        replacements.append((intake_id, "<INTAKE-ID>"))
    normalized = text
    for old, new in sorted(replacements, key=lambda item: len(item[0]), reverse=True):
        normalized = normalized.replace(old, new)
    return normalized


def _normalize_json(
    value: Any,
    *,
    work_root: Path,
    source: Path | None,
    landing: Path | None,
    intake_id: str | None,
) -> Any:
    if isinstance(value, str):
        return _normalize_text(
            value,
            work_root=work_root,
            source=source,
            landing=landing,
            intake_id=intake_id,
        )
    if isinstance(value, list):
        return [
            _normalize_json(
                item,
                work_root=work_root,
                source=source,
                landing=landing,
                intake_id=intake_id,
            )
            for item in value
        ]
    if isinstance(value, dict):
        return {
            key: _normalize_json(
                item,
                work_root=work_root,
                source=source,
                landing=landing,
                intake_id=intake_id,
            )
            for key, item in value.items()
        }
    return value


def _json_or_none(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _raises_message(callback: Callable[[], Any]) -> str:
    try:
        callback()
    except Exception as exc:
        return str(exc)
    raise AssertionError("callback did not raise")


def _dataclass_shape(cls: type[Any]) -> dict[str, Any]:
    return {
        "fields": [
            {
                "name": field.name,
                "default": _field_default(field),
            }
            for field in dataclasses.fields(cls)
        ],
        "properties": sorted(
            name for name, value in vars(cls).items() if isinstance(value, property)
        ),
        "methods": {
            name: str(inspect.signature(value))
            for name, value in sorted(vars(cls).items())
            if callable(value) and not name.startswith("_")
        },
    }


def _field_default(field: dataclasses.Field[Any]) -> Any:
    if field.default is not dataclasses.MISSING:
        return _jsonable(field.default)
    if field.default_factory is not dataclasses.MISSING:  # type: ignore[comparison-overlap]
        return "<factory>"
    return "<required>"


def _module_defined_exports(module: Any) -> list[str]:
    exports = []
    for name in dir(module):
        if name.startswith("_"):
            continue
        value = getattr(module, name)
        if getattr(value, "__module__", None) == module.__name__ or name.isupper():
            exports.append(name)
    return sorted(exports)


def _module_signatures(module: Any) -> dict[str, str]:
    signatures = {}
    for name in _module_defined_exports(module):
        value = getattr(module, name)
        if inspect.isclass(value) or callable(value):
            with contextlib.suppress(TypeError, ValueError):
                signatures[name] = str(inspect.signature(value))
    return signatures


def _qualified_name(value: Any) -> str:
    return f"{value.__module__}.{value.__qualname__}"


def _jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, tuple):
        return [_jsonable(item) for item in value]
    if isinstance(value, frozenset):
        return sorted(_jsonable(item) for item in value)
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return repr(value)


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    """Generate and write the receive fixture corpus."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_FIXTURE_ROOT,
        help="Fixture directory to write. Defaults to the package fixture dir.",
    )
    args = parser.parse_args(argv)
    with tempfile.TemporaryDirectory(prefix="receive-fixtures-") as raw_tmp:
        work_root = Path(raw_tmp)
        corpus = build_corpus(work_root)
    if args.output.exists():
        shutil.rmtree(args.output)
    write_corpus(corpus, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
