"""schema hardening wave 1

Revision ID: 9472dbefdaff
Revises: f2a3b4c5d6e7
Create Date: 2026-07-20 15:56:12.769524

"""

from collections.abc import Sequence
import datetime as dt

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from sutradhara.catalog.media_identity import _copy_media_id
from sutradhara.schema_conventions import vocabulary_check_sql

# revision identifiers, used by Alembic.
revision: str = "9472dbefdaff"
down_revision: str | Sequence[str] | None = "f2a3b4c5d6e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def _batch(table_name: str, *, schema: str | None = None):
    """Open a batch operation with stable names for reflected legacy FKs."""

    return op.batch_alter_table(
        table_name,
        schema=schema,
        naming_convention=_NAMING_CONVENTION,
    )


def _recreate_copy_health_trigger() -> None:
    """Restore the SQLite trigger lost when batch mode rebuilds ``copy``."""

    if op.get_bind().dialect.name != "sqlite":
        return
    op.execute("DROP TRIGGER IF EXISTS trg_copy_health_changed_at")
    op.execute(
        "CREATE TRIGGER trg_copy_health_changed_at "
        "AFTER UPDATE OF health ON copy "
        "FOR EACH ROW WHEN NEW.health IS NOT OLD.health "
        "BEGIN UPDATE copy SET health_changed_at = CURRENT_TIMESTAMP WHERE id = NEW.id; END"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifactclass",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    _backfill_artifactclasses()
    op.create_table(
        "asset_review_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("logical_asset_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            vocabulary_check_sql("action", "asset_review_action"),
            name="ck_asset_review_event_action",
        ),
        sa.ForeignKeyConstraint(
            ["logical_asset_hash"], ["logical_asset.content_sha256"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("asset_review_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_review_event_logical_asset_hash"),
            ["logical_asset_hash"],
            unique=False,
        )

    _backfill_asset_review_events()

    with op.batch_alter_table("blob_root", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blob_root_bundle_id"))
        batch_op.drop_index(batch_op.f("ix_blob_root_copy_id"))
        batch_op.drop_index(batch_op.f("ix_blob_root_pool_id"))

    op.drop_table("blob_root")
    with op.batch_alter_table(
        "arrangement", schema=None, naming_convention=_NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("abandoned_by", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("abandonment_reason", sa.Text(), nullable=True))

    op.execute(
        "UPDATE arrangement SET status = 'draft' WHERE status IN ('pending_derivatives', 'ready')"
    )
    op.execute(
        "UPDATE arrangement SET abandoned_at = updated_at, abandoned_by = 'legacy-unknown' "
        "WHERE status = 'abandoned'"
    )
    with op.batch_alter_table(
        "arrangement", schema=None, naming_convention=_NAMING_CONVENTION
    ) as batch_op:
        batch_op.create_foreign_key(
            "fk_arrangement_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )
        batch_op.drop_constraint("ck_arrangement_status", type_="check")
        batch_op.create_check_constraint(
            "ck_arrangement_status", vocabulary_check_sql("status", "arrangement_status")
        )
        batch_op.create_check_constraint(
            "ck_arrangement_abandonment",
            "(status = 'abandoned' AND abandoned_at IS NOT NULL AND abandoned_by IS NOT NULL) OR "
            "(status != 'abandoned' AND abandoned_at IS NULL AND abandoned_by IS NULL "
            "AND abandonment_reason IS NULL)",
        )

    with _batch("arrangement_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_arrangement_member_ingest_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_arrangement_member_ingest_item_id_ingest_item",
            "ingest_item",
            ["ingest_item_id"],
            ["id"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("artifactclass_policy", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_artifactclass_policy_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("artifactclass_pool", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_artifactclass_pool_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("logical_asset", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_logical_asset_media_kind",
            vocabulary_check_sql("media_kind", "media_kind"),
        )

    with op.batch_alter_table("backend", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_backend_tier", vocabulary_check_sql("tier", "backend_tier")
        )

    with _batch("asset_derivation", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_asset_derivation_source_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_asset_derivation_derived_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_asset_derivation_source_item_id_ingest_item",
            "ingest_item",
            ["source_item_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_asset_derivation_derived_item_id_ingest_item",
            "ingest_item",
            ["derived_item_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            "ck_asset_derivation_kind", vocabulary_check_sql("kind", "asset_derivation_kind")
        )

    with op.batch_alter_table("bundle_member", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_bundle_member_bundle_asset_path",
            ["bundle_id", "logical_asset_hash", "member_path"],
        )
        batch_op.create_unique_constraint(
            "uq_bundle_member_id_bundle_asset",
            ["id", "bundle_id", "logical_asset_hash"],
        )

    with op.batch_alter_table("copy", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_copy_id_pool_bundle", ["id", "pool_id", "bundle_id"])

    _assert_asset_locator_links()
    with _batch("asset_locator", schema=None) as batch_op:
        batch_op.alter_column("copy_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("bundle_id", existing_type=sa.VARCHAR(length=128), nullable=False)
        batch_op.drop_constraint(
            "fk_asset_locator_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_asset_locator_copy_id_copy", type_="foreignkey")
        batch_op.drop_constraint("fk_asset_locator_bundle_id_bundle", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_asset_locator_copy_pool_bundle",
            "copy",
            ["copy_id", "pool_id", "bundle_id"],
            ["id", "pool_id", "bundle_id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_asset_locator_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_asset_locator_bundle_id_bundle",
            "bundle",
            ["bundle_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_asset_locator_bundle_member",
            "bundle_member",
            ["bundle_id", "logical_asset_hash", "member_path"],
            ["bundle_id", "logical_asset_hash", "member_path"],
            ondelete="RESTRICT",
        )

    _strip_locator_member_paths()

    with _batch("asset_tag", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_asset_tag_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_asset_tag_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("bundle", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_bundle_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            "ck_bundle_status", vocabulary_check_sql("status", "bundle_status")
        )

    with _batch("bundle_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_bundle_member_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_bundle_member_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )

    with _batch("cache_entry", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cache_entry_content_sha256_logical_asset", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_cache_entry_content_sha256_logical_asset",
            "logical_asset",
            ["content_sha256"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_cache_entry_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with _batch("copy", schema=None) as batch_op:
        batch_op.add_column(sa.Column("media_id", sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column("media_family", sa.String(length=64), nullable=True))
        batch_op.drop_constraint(batch_op.f("fk_copy_bundle_id_bundle"), type_="foreignkey")
        batch_op.drop_constraint("fk_copy_backend_id_backend", type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_copy_pool_id_pool"), type_="foreignkey")
        batch_op.drop_constraint("fk_copy_logical_asset_hash_logical_asset", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_copy_backend_id_backend", "backend", ["backend_id"], ["id"], ondelete="RESTRICT"
        )
        batch_op.create_foreign_key(
            "fk_copy_bundle_id_bundle", "bundle", ["bundle_id"], ["id"], ondelete="RESTRICT"
        )
        batch_op.create_foreign_key(
            "fk_copy_pool_id_pool", "pool", ["pool_id"], ["id"], ondelete="RESTRICT"
        )
        batch_op.create_foreign_key(
            "fk_copy_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            "ck_copy_source", vocabulary_check_sql("source", "copy_source")
        )

    _backfill_copy_media_identity()
    with op.batch_alter_table("copy", schema=None) as batch_op:
        batch_op.alter_column("media_id", existing_type=sa.String(length=512), nullable=False)
        batch_op.alter_column("media_family", existing_type=sa.String(length=64), nullable=False)
        batch_op.create_index(batch_op.f("ix_copy_media_family"), ["media_family"], unique=False)
        batch_op.create_index(batch_op.f("ix_copy_media_id"), ["media_id"], unique=False)

    with op.batch_alter_table("exclusion_record", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_exclusion_record_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("grpc_intake", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_grpc_intake_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with _batch("ingest_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_path", sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column("pfr_sidecar_path", sa.String(length=4096), nullable=True))
        batch_op.drop_constraint(
            "fk_ingest_item_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_ingest_item_prior_intake_id_intake"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_ingest_item_prior_intake_id_intake",
            "intake",
            ["prior_intake_id"],
            ["intake_id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_ingest_item_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_ingest_item_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    _backfill_ingest_typed_paths()

    with op.batch_alter_table("intake", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_intake_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )
        batch_op.alter_column(
            "retention_state",
            existing_type=sa.String(length=32),
            server_default="not_applicable",
            existing_nullable=False,
        )
        batch_op.drop_constraint("ck_intake_status", type_="check")
        batch_op.drop_constraint("ck_intake_retention_state", type_="check")

    op.execute("UPDATE intake SET status = 'verifying' WHERE status = 'receiving'")
    op.execute("UPDATE intake SET retention_state = 'not_applicable' WHERE status != 'registered'")
    with op.batch_alter_table("intake", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_intake_status", vocabulary_check_sql("status", "intake_status")
        )
        batch_op.create_check_constraint(
            "ck_intake_retention_state",
            vocabulary_check_sql("retention_state", "retention_state"),
        )
        batch_op.create_check_constraint(
            "ck_intake_retention_ordering",
            "(status = 'registered' AND retention_state != 'not_applicable') OR "
            "(status != 'registered' AND retention_state = 'not_applicable')",
        )

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_job_status",
            vocabulary_check_sql("status", "job_status"),
        )

    with op.batch_alter_table("job_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subject_job_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("subject_domain", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("subject_key", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("params_snapshot", sa.JSON(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_job_attempt_subject_job_id"), ["subject_job_id"], unique=False
        )
        batch_op.create_check_constraint(
            "ck_job_attempt_outcome", vocabulary_check_sql("outcome", "job_attempt_outcome")
        )

    _backfill_job_attempt_subjects()

    with op.batch_alter_table("pool", schema=None) as batch_op:
        batch_op.add_column(sa.Column("storage_class", sa.String(length=64), nullable=True))
        batch_op.alter_column("location", existing_type=sa.VARCHAR(length=256), nullable=True)
        batch_op.drop_constraint(batch_op.f("uq_pool_backend_id"), type_="unique")

    op.execute("UPDATE pool SET storage_class = NULLIF(tier, ''), location = NULLIF(location, '')")
    with op.batch_alter_table("pool", schema=None) as batch_op:
        batch_op.drop_column("tier")

    with op.batch_alter_table("reconciliation_condition", schema=None) as batch_op:
        batch_op.add_column(sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("condition_changed_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("reopened_by", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("reopened_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_check_constraint(
            "ck_reconciliation_condition_observed_state",
            vocabulary_check_sql("observed_state", "observed_state"),
        )
        batch_op.create_check_constraint(
            "ck_reconciliation_condition_condition",
            vocabulary_check_sql("condition", "derivation_condition"),
        )

    op.execute(
        "UPDATE reconciliation_condition SET observed_at = updated_at, "
        "condition_changed_at = updated_at"
    )
    with op.batch_alter_table("reconciliation_condition", schema=None) as batch_op:
        batch_op.alter_column(
            "observed_at", existing_type=sa.DateTime(timezone=True), nullable=False
        )
        batch_op.alter_column(
            "condition_changed_at", existing_type=sa.DateTime(timezone=True), nullable=False
        )

    with _batch("restore_request_item", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_restore_request_item_content_sha256_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_restore_request_item_content_sha256_logical_asset",
            "logical_asset",
            ["content_sha256"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_restore_request_item_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("retention_event", schema=None) as batch_op:
        batch_op.alter_column("at", new_column_name="occurred_at", existing_type=sa.DateTime())

    with _batch("review_decision", schema=None) as batch_op:
        batch_op.drop_constraint("fk_review_decision_bundle_id_bundle", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_review_decision_bundle_id_bundle",
            "bundle",
            ["bundle_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            "ck_review_decision_action",
            vocabulary_check_sql("action", "review_action"),
        )
        batch_op.create_check_constraint(
            "ck_review_decision_scope", vocabulary_check_sql("scope", "review_scope")
        )

    with _batch("staging_transform", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_staging_transform_bundle_member_id_bundle_member", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_staging_transform_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_staging_transform_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_staging_transform_member_identity",
            "bundle_member",
            ["bundle_member_id", "bundle_id", "logical_asset_hash"],
            ["id", "bundle_id", "logical_asset_hash"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_staging_transform_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_submission_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )

    _assert_no_null_submission_members()
    with _batch("submission_member", schema=None) as batch_op:
        batch_op.alter_column("ingest_item_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_constraint(
            "fk_submission_member_ingest_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_submission_member_ingest_item_id_ingest_item",
            "ingest_item",
            ["ingest_item_id"],
            ["id"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("verify_receipt", schema=None) as batch_op:
        batch_op.alter_column("at", new_column_name="recorded_at", existing_type=sa.DateTime())

    with _batch("virtual_arrangement_history", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_va_member_id_virtual_arrangement_member",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_va_id_virtual_arrangement", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_va_member_id_virtual_arrangement_member",
            "virtual_arrangement_member",
            ["va_member_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_va_id_virtual_arrangement",
            "virtual_arrangement",
            ["va_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )

    with _batch("virtual_arrangement_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_virtual_arrangement_member_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_member_artifactclass_artifactclass",
            "artifactclass",
            ["artifactclass"],
            ["name"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_member_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="RESTRICT",
        )

    _recreate_copy_health_trigger()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with _batch("virtual_arrangement_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_virtual_arrangement_member_artifactclass_artifactclass", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_virtual_arrangement_member_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_member_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )

    with _batch("virtual_arrangement_history", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_artifactclass_artifactclass", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_va_id_virtual_arrangement", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_virtual_arrangement_history_va_member_id_virtual_arrangement_member",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_va_id_virtual_arrangement",
            "virtual_arrangement",
            ["va_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_virtual_arrangement_history_va_member_id_virtual_arrangement_member",
            "virtual_arrangement_member",
            ["va_member_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("verify_receipt", schema=None) as batch_op:
        batch_op.alter_column("recorded_at", new_column_name="at", existing_type=sa.DateTime())

    with _batch("submission_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_submission_member_ingest_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_submission_member_ingest_item_id_ingest_item",
            "ingest_item",
            ["ingest_item_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.alter_column("ingest_item_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.drop_constraint("fk_submission_artifactclass_artifactclass", type_="foreignkey")

    with _batch("staging_transform", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_staging_transform_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_staging_transform_member_identity", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_staging_transform_artifactclass_artifactclass", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_staging_transform_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_staging_transform_bundle_member_id_bundle_member",
            "bundle_member",
            ["bundle_member_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with _batch("review_decision", schema=None) as batch_op:
        batch_op.drop_constraint("fk_review_decision_bundle_id_bundle", type_="foreignkey")
        batch_op.drop_constraint("ck_review_decision_action", type_="check")
        batch_op.drop_constraint("ck_review_decision_scope", type_="check")
        batch_op.create_foreign_key(
            "fk_review_decision_bundle_id_bundle",
            "bundle",
            ["bundle_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("retention_event", schema=None) as batch_op:
        batch_op.alter_column("occurred_at", new_column_name="at", existing_type=sa.DateTime())

    with _batch("restore_request_item", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_restore_request_item_content_sha256_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_restore_request_item_artifactclass_artifactclass", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_restore_request_item_content_sha256_logical_asset",
            "logical_asset",
            ["content_sha256"],
            ["content_sha256"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("reconciliation_condition", schema=None) as batch_op:
        batch_op.drop_constraint("ck_reconciliation_condition_observed_state", type_="check")
        batch_op.drop_constraint("ck_reconciliation_condition_condition", type_="check")
        batch_op.drop_column("reopened_at")
        batch_op.drop_column("reopened_by")
        batch_op.drop_column("condition_changed_at")
        batch_op.drop_column("observed_at")

    with op.batch_alter_table("pool", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tier", sa.VARCHAR(length=64), nullable=True))

    op.execute(
        "UPDATE pool SET tier = COALESCE(storage_class, ''), location = COALESCE(location, '')"
    )
    with op.batch_alter_table("pool", schema=None) as batch_op:
        batch_op.alter_column("tier", existing_type=sa.String(length=64), nullable=False)
        batch_op.create_unique_constraint(batch_op.f("uq_pool_backend_id"), ["backend_id", "id"])
        batch_op.alter_column("location", existing_type=sa.VARCHAR(length=256), nullable=False)
        batch_op.drop_column("storage_class")

    with op.batch_alter_table("job_attempt", schema=None) as batch_op:
        batch_op.drop_constraint("ck_job_attempt_outcome", type_="check")
        batch_op.drop_index(batch_op.f("ix_job_attempt_subject_job_id"))
        batch_op.drop_column("params_snapshot")
        batch_op.drop_column("subject_key")
        batch_op.drop_column("subject_domain")
        batch_op.drop_column("subject_job_id")

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_constraint("ck_job_status", type_="check")

    with op.batch_alter_table("intake", schema=None) as batch_op:
        batch_op.drop_constraint("fk_intake_artifactclass_artifactclass", type_="foreignkey")
        batch_op.drop_constraint("ck_intake_retention_ordering", type_="check")
        batch_op.drop_constraint("ck_intake_retention_state", type_="check")
        batch_op.drop_constraint("ck_intake_status", type_="check")
        batch_op.alter_column(
            "retention_state",
            existing_type=sa.String(length=32),
            server_default="held",
            existing_nullable=False,
        )

    op.execute(
        "UPDATE intake SET retention_state = 'held' WHERE retention_state = 'not_applicable'"
    )
    with op.batch_alter_table("intake", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_intake_status",
            "status IN ('receiving', 'verifying', 'quarantined', 'registered')",
        )
        batch_op.create_check_constraint(
            "ck_intake_retention_state",
            "retention_state IN ('held', 'released', 'tombstoned', 'abandoned', 'purged')",
        )

    _restore_ingest_typed_paths_to_metadata()
    with _batch("ingest_item", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ingest_item_artifactclass_artifactclass", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_ingest_item_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_ingest_item_prior_intake_id_intake", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_ingest_item_prior_intake_id_intake"),
            "intake",
            ["prior_intake_id"],
            ["intake_id"],
        )
        batch_op.create_foreign_key(
            "fk_ingest_item_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("pfr_sidecar_path")
        batch_op.drop_column("source_path")

    with op.batch_alter_table("grpc_intake", schema=None) as batch_op:
        batch_op.drop_constraint("fk_grpc_intake_artifactclass_artifactclass", type_="foreignkey")

    with op.batch_alter_table("exclusion_record", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_exclusion_record_artifactclass_artifactclass", type_="foreignkey"
        )

    with _batch("copy", schema=None) as batch_op:
        batch_op.drop_constraint("fk_copy_backend_id_backend", type_="foreignkey")
        batch_op.drop_constraint("fk_copy_bundle_id_bundle", type_="foreignkey")
        batch_op.drop_constraint("fk_copy_pool_id_pool", type_="foreignkey")
        batch_op.drop_constraint("fk_copy_logical_asset_hash_logical_asset", type_="foreignkey")
        batch_op.drop_constraint("ck_copy_source", type_="check")
        batch_op.create_foreign_key(
            "fk_copy_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_copy_pool_id_pool"), "pool", ["pool_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_copy_backend_id_backend", "backend", ["backend_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_copy_bundle_id_bundle"),
            "bundle",
            ["bundle_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_constraint("uq_copy_id_pool_bundle", type_="unique")
        batch_op.drop_index(batch_op.f("ix_copy_media_id"))
        batch_op.drop_index(batch_op.f("ix_copy_media_family"))
        batch_op.drop_column("media_family")
        batch_op.drop_column("media_id")

    with _batch("cache_entry", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cache_entry_artifactclass_artifactclass", type_="foreignkey")
        batch_op.drop_constraint("fk_cache_entry_content_sha256_logical_asset", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_cache_entry_content_sha256_logical_asset",
            "logical_asset",
            ["content_sha256"],
            ["content_sha256"],
            ondelete="CASCADE",
        )

    with _batch("bundle_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_bundle_member_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_bundle_member_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )
        batch_op.drop_constraint("uq_bundle_member_id_bundle_asset", type_="unique")
        batch_op.drop_constraint("uq_bundle_member_bundle_asset_path", type_="unique")

    with op.batch_alter_table("bundle", schema=None) as batch_op:
        batch_op.drop_constraint("fk_bundle_artifactclass_artifactclass", type_="foreignkey")
        batch_op.drop_constraint("ck_bundle_status", type_="check")

    with _batch("asset_tag", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_asset_tag_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_asset_tag_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )

    _restore_locator_member_paths()
    with _batch("asset_locator", schema=None) as batch_op:
        batch_op.drop_constraint("fk_asset_locator_bundle_member", type_="foreignkey")
        batch_op.drop_constraint("fk_asset_locator_bundle_id_bundle", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_asset_locator_logical_asset_hash_logical_asset", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_asset_locator_copy_pool_bundle", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_asset_locator_bundle_id_bundle",
            "bundle",
            ["bundle_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_asset_locator_copy_id_copy", "copy", ["copy_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_asset_locator_logical_asset_hash_logical_asset",
            "logical_asset",
            ["logical_asset_hash"],
            ["content_sha256"],
            ondelete="CASCADE",
        )
        batch_op.alter_column("bundle_id", existing_type=sa.VARCHAR(length=128), nullable=True)
        batch_op.alter_column("copy_id", existing_type=sa.INTEGER(), nullable=True)

    with _batch("asset_derivation", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_asset_derivation_source_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_asset_derivation_derived_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.drop_constraint("ck_asset_derivation_kind", type_="check")
        batch_op.create_foreign_key(
            "fk_asset_derivation_source_item_id_ingest_item",
            "ingest_item",
            ["source_item_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_asset_derivation_derived_item_id_ingest_item",
            "ingest_item",
            ["derived_item_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("backend", schema=None) as batch_op:
        batch_op.drop_constraint("ck_backend_tier", type_="check")

    with op.batch_alter_table("logical_asset", schema=None) as batch_op:
        batch_op.drop_constraint("ck_logical_asset_media_kind", type_="check")

    with op.batch_alter_table("artifactclass_pool", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_artifactclass_pool_artifactclass_artifactclass", type_="foreignkey"
        )

    with op.batch_alter_table("artifactclass_policy", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_artifactclass_policy_artifactclass_artifactclass", type_="foreignkey"
        )

    with _batch("arrangement_member", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_arrangement_member_ingest_item_id_ingest_item", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_arrangement_member_ingest_item_id_ingest_item",
            "ingest_item",
            ["ingest_item_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("arrangement", schema=None) as batch_op:
        batch_op.drop_constraint("fk_arrangement_artifactclass_artifactclass", type_="foreignkey")
        batch_op.drop_constraint("ck_arrangement_abandonment", type_="check")
        batch_op.drop_constraint("ck_arrangement_status", type_="check")
        batch_op.create_check_constraint(
            "ck_arrangement_status",
            "status IN ('draft', 'pending_derivatives', 'ready', 'submitted', 'abandoned')",
        )
        batch_op.drop_column("abandonment_reason")
        batch_op.drop_column("abandoned_by")
        batch_op.drop_column("abandoned_at")

    op.create_table(
        "blob_root",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("bundle_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("copy_id", sa.INTEGER(), nullable=False),
        sa.Column("pool_id", sa.VARCHAR(length=128), nullable=False),
        sa.Column("root_path", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("native_locator", sqlite.JSON(), nullable=False),
        sa.Column("archive_id", sa.VARCHAR(length=128), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["bundle_id"], ["bundle.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["copy_id"], ["copy.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pool_id"], ["pool.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("copy_id", "root_path", name=op.f("uq_blob_root_copy_root")),
    )
    with op.batch_alter_table("blob_root", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blob_root_pool_id"), ["pool_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_blob_root_copy_id"), ["copy_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_blob_root_bundle_id"), ["bundle_id"], unique=False)

    with op.batch_alter_table("asset_review_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_review_event_logical_asset_hash"))

    op.drop_table("asset_review_event")
    op.drop_table("artifactclass")
    _recreate_copy_health_trigger()
    # ### end Alembic commands ###


_ARTIFACTCLASS_TABLES = (
    "intake",
    "ingest_item",
    "arrangement",
    "submission",
    "virtual_arrangement_member",
    "virtual_arrangement_history",
    "artifactclass_pool",
    "artifactclass_policy",
    "bundle",
    "staging_transform",
    "exclusion_record",
    "grpc_intake",
    "cache_entry",
    "restore_request_item",
)


def _backfill_artifactclasses() -> None:
    """Seed the registry from every existing artifactclass-bearing table."""

    connection = op.get_bind()
    names: set[str] = set()
    for table_name in _ARTIFACTCLASS_TABLES:
        rows = connection.execute(sa.text(f"SELECT DISTINCT artifactclass FROM {table_name}"))
        names.update(str(value) for value in rows.scalars() if value)
    registry = sa.table(
        "artifactclass",
        sa.column("name", sa.String()),
        sa.column("created_at", sa.DateTime()),
    )
    if names:
        now = dt.datetime.now(dt.UTC)
        connection.execute(
            registry.insert(),
            [{"name": name, "created_at": now} for name in sorted(names)],
        )


def _backfill_asset_review_events() -> None:
    """Preserve pre-Wave-1 rejection attribution as append-only events."""

    connection = op.get_bind()
    assets = sa.table(
        "logical_asset",
        sa.column("content_sha256", sa.LargeBinary()),
        sa.column("rejected_at", sa.DateTime()),
        sa.column("rejected_by", sa.String()),
        sa.column("rejection_reason", sa.Text()),
    )
    events = sa.table(
        "asset_review_event",
        sa.column("logical_asset_hash", sa.LargeBinary()),
        sa.column("action", sa.String()),
        sa.column("actor", sa.String()),
        sa.column("reason", sa.Text()),
        sa.column("decided_at", sa.DateTime()),
    )
    rows = connection.execute(
        sa.select(
            assets.c.content_sha256,
            assets.c.rejected_at,
            assets.c.rejected_by,
            assets.c.rejection_reason,
        ).where(assets.c.rejected_at.is_not(None))
    ).mappings()
    payload = [
        {
            "logical_asset_hash": row.content_sha256,
            "action": "reject",
            "actor": row.rejected_by or "legacy-unknown",
            "reason": row.rejection_reason,
            "decided_at": row.rejected_at,
        }
        for row in rows
    ]
    if payload:
        connection.execute(events.insert(), payload)


def _backfill_copy_media_identity() -> None:
    """Materialize identity with the same pure derivation used by registration."""

    connection = op.get_bind()
    copies = sa.table(
        "copy",
        sa.column("id", sa.Integer()),
        sa.column("backend_id", sa.Integer()),
        sa.column("native_locator", sa.JSON()),
        sa.column("media_id", sa.String()),
        sa.column("media_family", sa.String()),
    )
    backends = sa.table(
        "backend",
        sa.column("id", sa.Integer()),
        sa.column("implementation_family", sa.String()),
    )
    rows = connection.execute(
        sa.select(
            copies.c.id,
            copies.c.backend_id,
            copies.c.native_locator,
            backends.c.implementation_family,
        ).join(backends, backends.c.id == copies.c.backend_id)
    ).mappings()
    for row in rows:
        identity = _copy_media_id(
            row.implementation_family,
            row.native_locator,
            row.backend_id,
        )
        connection.execute(
            copies.update()
            .where(copies.c.id == row.id)
            .values(media_id=identity.media_id, media_family=identity.media_family)
        )


def _backfill_ingest_typed_paths() -> None:
    """Promote path facts and remove their obsolete JSON aliases."""

    connection = op.get_bind()
    items = sa.table(
        "ingest_item",
        sa.column("id", sa.Integer()),
        sa.column("metadata", sa.JSON()),
        sa.column("source_path", sa.String()),
        sa.column("pfr_sidecar_path", sa.String()),
    )
    rows = connection.execute(sa.select(items.c.id, items.c.metadata)).mappings()
    for row in rows:
        metadata = dict(row.metadata or {})
        source_path = metadata.pop("source_path", None)
        sidecar_path = metadata.pop("pfr_sidecar_path", None)
        metadata.pop("sha256", None)
        connection.execute(
            items.update()
            .where(items.c.id == row.id)
            .values(
                source_path=source_path if isinstance(source_path, str) else None,
                pfr_sidecar_path=sidecar_path if isinstance(sidecar_path, str) else None,
                metadata=metadata,
            )
        )


def _strip_locator_member_paths() -> None:
    """Keep member_path only in its typed locator column."""

    connection = op.get_bind()
    locators = sa.table(
        "asset_locator",
        sa.column("id", sa.Integer()),
        sa.column("native_locator", sa.JSON()),
    )
    rows = connection.execute(sa.select(locators.c.id, locators.c.native_locator)).mappings()
    for row in rows:
        native_locator = dict(row.native_locator or {})
        native_locator.pop("member_path", None)
        connection.execute(
            locators.update().where(locators.c.id == row.id).values(native_locator=native_locator)
        )


def _restore_ingest_typed_paths_to_metadata() -> None:
    """Rebuild the legacy JSON aliases before dropping promoted columns."""

    connection = op.get_bind()
    items = sa.table(
        "ingest_item",
        sa.column("id", sa.Integer()),
        sa.column("logical_asset_hash", sa.LargeBinary()),
        sa.column("metadata", sa.JSON()),
        sa.column("source_path", sa.String()),
        sa.column("pfr_sidecar_path", sa.String()),
    )
    rows = connection.execute(
        sa.select(
            items.c.id,
            items.c.logical_asset_hash,
            items.c.metadata,
            items.c.source_path,
            items.c.pfr_sidecar_path,
        )
    ).mappings()
    for row in rows:
        metadata = dict(row.metadata or {})
        if row.source_path is not None:
            metadata["source_path"] = row.source_path
        if row.pfr_sidecar_path is not None:
            metadata["pfr_sidecar_path"] = row.pfr_sidecar_path
        if row.logical_asset_hash is not None:
            metadata["sha256"] = bytes(row.logical_asset_hash).hex()
        connection.execute(items.update().where(items.c.id == row.id).values(metadata=metadata))


def _restore_locator_member_paths() -> None:
    """Rebuild the legacy locator JSON alias before downgrade."""

    connection = op.get_bind()
    locators = sa.table(
        "asset_locator",
        sa.column("id", sa.Integer()),
        sa.column("member_path", sa.String()),
        sa.column("native_locator", sa.JSON()),
    )
    rows = connection.execute(
        sa.select(locators.c.id, locators.c.member_path, locators.c.native_locator)
    ).mappings()
    for row in rows:
        native_locator = dict(row.native_locator or {})
        native_locator["member_path"] = row.member_path
        connection.execute(
            locators.update().where(locators.c.id == row.id).values(native_locator=native_locator)
        )


def _backfill_job_attempt_subjects() -> None:
    """Snapshot legacy job identity and parameters before jobs can be pruned."""

    connection = op.get_bind()
    attempts = sa.table(
        "job_attempt",
        sa.column("id", sa.Integer()),
        sa.column("job_id", sa.Integer()),
        sa.column("subject_job_id", sa.Integer()),
        sa.column("subject_domain", sa.String()),
        sa.column("subject_key", sa.String()),
        sa.column("params_snapshot", sa.JSON()),
    )
    jobs = sa.table(
        "job",
        sa.column("id", sa.Integer()),
        sa.column("params", sa.JSON()),
        sa.column("recon_domain", sa.String()),
        sa.column("recon_target_key", sa.String()),
    )
    rows = connection.execute(
        sa.select(
            attempts.c.id,
            attempts.c.job_id,
            jobs.c.params,
            jobs.c.recon_domain,
            jobs.c.recon_target_key,
        ).select_from(attempts.outerjoin(jobs, jobs.c.id == attempts.c.job_id))
    ).mappings()
    for row in rows:
        connection.execute(
            attempts.update()
            .where(attempts.c.id == row.id)
            .values(
                subject_job_id=row.job_id,
                subject_domain=row.recon_domain,
                subject_key=row.recon_target_key,
                params_snapshot=(sa.null() if row.job_id is None else dict(row.params or {})),
            )
        )


def _assert_asset_locator_links() -> None:
    """Refuse to invent the copy or bundle identity of legacy locators."""

    count = op.get_bind().scalar(
        sa.text("SELECT count(*) FROM asset_locator WHERE copy_id IS NULL OR bundle_id IS NULL")
    )
    if count:
        raise RuntimeError("asset_locator contains rows without copy_id/bundle_id")


def _assert_no_null_submission_members() -> None:
    """Refuse to discard immutable submission provenance during hardening."""

    count = op.get_bind().scalar(
        sa.text("SELECT count(*) FROM submission_member WHERE ingest_item_id IS NULL")
    )
    if count:
        raise RuntimeError("submission_member contains rows without ingest_item_id")
