"""initial: logical_asset + backend + copy

Revision ID: ea7254a77d7a
Revises: 
Create Date: 2026-05-27 19:00:39.525286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7254a77d7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('logical_asset',
    sa.Column('content_sha256', sa.LargeBinary(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('human_label', sa.String(length=512), nullable=True),
    sa.Column('media_kind', sa.String(length=32), nullable=True),
    sa.Column('media_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('content_sha256')
    )
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logical_asset_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=False),
    sa.Column('native_locator', sa.JSON(), nullable=False),
    sa.Column('native_locator_key', sa.String(length=512), nullable=False),
    sa.Column('integrity_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['backend.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logical_asset_hash'], ['logical_asset.content_sha256'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backend_id', 'native_locator_key', name='uq_copy_backend_locator')
    )
    with op.batch_alter_table('copy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copy_backend_id'), ['backend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copy_logical_asset_hash'), ['logical_asset_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copy_logical_asset_hash'))
        batch_op.drop_index(batch_op.f('ix_copy_backend_id'))

    op.drop_table('copy')
    op.drop_table('logical_asset')
    op.drop_table('backend')
    # ### end Alembic commands ###
