# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import intake_pb2 as intake__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in intake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntakeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartIntake = channel.unary_unary(
                '/sutradhara.intake.IntakeService/StartIntake',
                request_serializer=intake__pb2.StartIntakeRequest.SerializeToString,
                response_deserializer=intake__pb2.StartIntakeResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/sutradhara.intake.IntakeService/UploadFile',
                request_serializer=intake__pb2.FileChunk.SerializeToString,
                response_deserializer=intake__pb2.FileReceipt.FromString,
                _registered_method=True)
        self.ListIntakeFiles = channel.unary_unary(
                '/sutradhara.intake.IntakeService/ListIntakeFiles',
                request_serializer=intake__pb2.ListIntakeFilesRequest.SerializeToString,
                response_deserializer=intake__pb2.ListIntakeFilesResponse.FromString,
                _registered_method=True)
        self.CommitIntake = channel.unary_unary(
                '/sutradhara.intake.IntakeService/CommitIntake',
                request_serializer=intake__pb2.CommitIntakeRequest.SerializeToString,
                response_deserializer=intake__pb2.CommitIntakeResponse.FromString,
                _registered_method=True)
        self.GetIntakeStatus = channel.unary_unary(
                '/sutradhara.intake.IntakeService/GetIntakeStatus',
                request_serializer=intake__pb2.IntakeStatusRequest.SerializeToString,
                response_deserializer=intake__pb2.IntakeStatusResponse.FromString,
                _registered_method=True)
        self.AbortIntake = channel.unary_unary(
                '/sutradhara.intake.IntakeService/AbortIntake',
                request_serializer=intake__pb2.AbortIntakeRequest.SerializeToString,
                response_deserializer=intake__pb2.AbortIntakeResponse.FromString,
                _registered_method=True)


class IntakeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartIntake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIntakeFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitIntake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntakeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortIntake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntakeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartIntake': grpc.unary_unary_rpc_method_handler(
                    servicer.StartIntake,
                    request_deserializer=intake__pb2.StartIntakeRequest.FromString,
                    response_serializer=intake__pb2.StartIntakeResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=intake__pb2.FileChunk.FromString,
                    response_serializer=intake__pb2.FileReceipt.SerializeToString,
            ),
            'ListIntakeFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIntakeFiles,
                    request_deserializer=intake__pb2.ListIntakeFilesRequest.FromString,
                    response_serializer=intake__pb2.ListIntakeFilesResponse.SerializeToString,
            ),
            'CommitIntake': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitIntake,
                    request_deserializer=intake__pb2.CommitIntakeRequest.FromString,
                    response_serializer=intake__pb2.CommitIntakeResponse.SerializeToString,
            ),
            'GetIntakeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntakeStatus,
                    request_deserializer=intake__pb2.IntakeStatusRequest.FromString,
                    response_serializer=intake__pb2.IntakeStatusResponse.SerializeToString,
            ),
            'AbortIntake': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortIntake,
                    request_deserializer=intake__pb2.AbortIntakeRequest.FromString,
                    response_serializer=intake__pb2.AbortIntakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sutradhara.intake.IntakeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sutradhara.intake.IntakeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntakeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartIntake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutradhara.intake.IntakeService/StartIntake',
            intake__pb2.StartIntakeRequest.SerializeToString,
            intake__pb2.StartIntakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sutradhara.intake.IntakeService/UploadFile',
            intake__pb2.FileChunk.SerializeToString,
            intake__pb2.FileReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIntakeFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutradhara.intake.IntakeService/ListIntakeFiles',
            intake__pb2.ListIntakeFilesRequest.SerializeToString,
            intake__pb2.ListIntakeFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitIntake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutradhara.intake.IntakeService/CommitIntake',
            intake__pb2.CommitIntakeRequest.SerializeToString,
            intake__pb2.CommitIntakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntakeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutradhara.intake.IntakeService/GetIntakeStatus',
            intake__pb2.IntakeStatusRequest.SerializeToString,
            intake__pb2.IntakeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortIntake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutradhara.intake.IntakeService/AbortIntake',
            intake__pb2.AbortIntakeRequest.SerializeToString,
            intake__pb2.AbortIntakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
