# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import restore_pb2 as restore__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in restore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestoreServiceStub:
    """Shared server/RM2 restore-agent contract.

    CommitRestore(REVEALED) is terminal and idempotent whether or not the agent
    previously reported STAGED. committed_index is the count of complete files
    durably staged in manifest order. If a STAGED acknowledgement is lost, the
    server may re-stream from an older committed_index; the client MUST verify
    every received file, skip data it already knows is durable, and truncate the
    in-progress file before accepting its re-stream. RM1.3 implements these
    durable commit and resume rules; RM1.2a fixes their wire representation.

    Version 1 carries regular files only. mode/uid/gid/mtime are synthetic
    catalog-independent metadata. Xattrs and other entry types are out of v1.

    manifest_sha256 is SHA-256 over these bytes in order: the domain
    "sutradhara.restore.manifest.v1\0"; a big-endian uint32 file count; then,
    for each ordered entry, a big-endian uint32 UTF-8 path length, the path,
    a big-endian uint64 plaintext size, and the 32-byte plaintext content hash.
    The server freezes this digest before emitting any data frame.

    OpenRestore rejects a live open-session generation and supersedes only an
    expired generation. WatchAssignments polls admitted queued/sent agent items
    and emits each observed item once per watch. It is scoped to the authenticated
    mTLS peer: device_id MUST equal that peer's device id.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenRestore = channel.unary_stream(
                '/sutradhara.restore.RestoreService/OpenRestore',
                request_serializer=restore__pb2.OpenRestoreRequest.SerializeToString,
                response_deserializer=restore__pb2.RestoreFrame.FromString,
                _registered_method=True)
        self.CommitRestore = channel.unary_unary(
                '/sutradhara.restore.RestoreService/CommitRestore',
                request_serializer=restore__pb2.CommitRestoreRequest.SerializeToString,
                response_deserializer=restore__pb2.CommitRestoreReply.FromString,
                _registered_method=True)
        self.WatchAssignments = channel.unary_stream(
                '/sutradhara.restore.RestoreService/WatchAssignments',
                request_serializer=restore__pb2.WatchRequest.SerializeToString,
                response_deserializer=restore__pb2.Assignment.FromString,
                _registered_method=True)


class RestoreServiceServicer:
    """Shared server/RM2 restore-agent contract.

    CommitRestore(REVEALED) is terminal and idempotent whether or not the agent
    previously reported STAGED. committed_index is the count of complete files
    durably staged in manifest order. If a STAGED acknowledgement is lost, the
    server may re-stream from an older committed_index; the client MUST verify
    every received file, skip data it already knows is durable, and truncate the
    in-progress file before accepting its re-stream. RM1.3 implements these
    durable commit and resume rules; RM1.2a fixes their wire representation.

    Version 1 carries regular files only. mode/uid/gid/mtime are synthetic
    catalog-independent metadata. Xattrs and other entry types are out of v1.

    manifest_sha256 is SHA-256 over these bytes in order: the domain
    "sutradhara.restore.manifest.v1\0"; a big-endian uint32 file count; then,
    for each ordered entry, a big-endian uint32 UTF-8 path length, the path,
    a big-endian uint64 plaintext size, and the 32-byte plaintext content hash.
    The server freezes this digest before emitting any data frame.

    OpenRestore rejects a live open-session generation and supersedes only an
    expired generation. WatchAssignments polls admitted queued/sent agent items
    and emits each observed item once per watch. It is scoped to the authenticated
    mTLS peer: device_id MUST equal that peer's device id.
    """

    def OpenRestore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitRestore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAssignments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenRestore': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenRestore,
                    request_deserializer=restore__pb2.OpenRestoreRequest.FromString,
                    response_serializer=restore__pb2.RestoreFrame.SerializeToString,
            ),
            'CommitRestore': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitRestore,
                    request_deserializer=restore__pb2.CommitRestoreRequest.FromString,
                    response_serializer=restore__pb2.CommitRestoreReply.SerializeToString,
            ),
            'WatchAssignments': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAssignments,
                    request_deserializer=restore__pb2.WatchRequest.FromString,
                    response_serializer=restore__pb2.Assignment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sutradhara.restore.RestoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sutradhara.restore.RestoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestoreService:
    """Shared server/RM2 restore-agent contract.

    CommitRestore(REVEALED) is terminal and idempotent whether or not the agent
    previously reported STAGED. committed_index is the count of complete files
    durably staged in manifest order. If a STAGED acknowledgement is lost, the
    server may re-stream from an older committed_index; the client MUST verify
    every received file, skip data it already knows is durable, and truncate the
    in-progress file before accepting its re-stream. RM1.3 implements these
    durable commit and resume rules; RM1.2a fixes their wire representation.

    Version 1 carries regular files only. mode/uid/gid/mtime are synthetic
    catalog-independent metadata. Xattrs and other entry types are out of v1.

    manifest_sha256 is SHA-256 over these bytes in order: the domain
    "sutradhara.restore.manifest.v1\0"; a big-endian uint32 file count; then,
    for each ordered entry, a big-endian uint32 UTF-8 path length, the path,
    a big-endian uint64 plaintext size, and the 32-byte plaintext content hash.
    The server freezes this digest before emitting any data frame.

    OpenRestore rejects a live open-session generation and supersedes only an
    expired generation. WatchAssignments polls admitted queued/sent agent items
    and emits each observed item once per watch. It is scoped to the authenticated
    mTLS peer: device_id MUST equal that peer's device id.
    """

    @staticmethod
    def OpenRestore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sutradhara.restore.RestoreService/OpenRestore',
            restore__pb2.OpenRestoreRequest.SerializeToString,
            restore__pb2.RestoreFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitRestore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sutradhara.restore.RestoreService/CommitRestore',
            restore__pb2.CommitRestoreRequest.SerializeToString,
            restore__pb2.CommitRestoreReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAssignments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sutradhara.restore.RestoreService/WatchAssignments',
            restore__pb2.WatchRequest.SerializeToString,
            restore__pb2.Assignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
