"""Dependency-light front-door receive core.

The receive package owns the filesystem contract for Sutradhara's first-contact
intake path: canonical member names, BagIt manifests, atomic landing writes,
resume state, and server marker polling. It deliberately has no catalog,
backend, Remanence, or database dependencies so the same code can run on edge
clients and inside the server-side intake verifier.
"""

from sutradhara_receive.core import (
    BAG_INFO_NAME,
    BAG_PROFILE,
    CANONICALIZATION_VERSION,
    DATA_DIR_NAME,
    MANIFEST_NAME,
    PACKAGE_GLOBS,
    PACKAGE_INDEX_NAME,
    PACKAGE_PROFILE_HASH,
    PACKAGE_PROFILE_VERSION,
    RECEIVE_PACKAGE,
    RECEIVE_PACKAGE_NAME,
    RECEIVE_PACKAGE_VERSION,
    RECEIVE_VERSION,
    SUPPORTED_RECEIVE_PACKAGES,
    AtomicWriteObserver,
    BagValidationResult,
    BagWriteResult,
    CollisionError,
    ConfirmationResult,
    DestinationVerificationError,
    FileReceipt,
    OrphanSweepResult,
    PayloadPlan,
    PayloadUnit,
    ReceiveError,
    ReceiveResult,
    RejectedEntry,
    SourceMutationError,
    SourceScanError,
    bag_info_metadata,
    bag_info_text,
    bagit_manifest_text,
    canonicalize_filesystem_path,
    canonicalize_manifest_path,
    hash_payload_tree,
    manifest_mismatch,
    payload_plan_digest,
    plan_payload_units,
    read_bag_info,
    read_manifest_sha256,
    read_package_index,
    receive_source,
    safe_payload_path,
    sha256_file,
    slug_operator,
    sweep_orphans,
    tagmanifest_text,
    validate_bag,
    wait_for_server_confirmation,
    write_bagit_files,
)

__all__ = [
    "BAG_INFO_NAME",
    "BAG_PROFILE",
    "CANONICALIZATION_VERSION",
    "DATA_DIR_NAME",
    "MANIFEST_NAME",
    "PACKAGE_GLOBS",
    "PACKAGE_INDEX_NAME",
    "PACKAGE_PROFILE_HASH",
    "PACKAGE_PROFILE_VERSION",
    "RECEIVE_PACKAGE",
    "RECEIVE_PACKAGE_NAME",
    "RECEIVE_PACKAGE_VERSION",
    "RECEIVE_VERSION",
    "SUPPORTED_RECEIVE_PACKAGES",
    "AtomicWriteObserver",
    "BagValidationResult",
    "BagWriteResult",
    "CollisionError",
    "ConfirmationResult",
    "DestinationVerificationError",
    "FileReceipt",
    "OrphanSweepResult",
    "PayloadPlan",
    "PayloadUnit",
    "ReceiveError",
    "ReceiveResult",
    "RejectedEntry",
    "SourceMutationError",
    "SourceScanError",
    "bag_info_metadata",
    "bag_info_text",
    "bagit_manifest_text",
    "canonicalize_filesystem_path",
    "canonicalize_manifest_path",
    "hash_payload_tree",
    "manifest_mismatch",
    "payload_plan_digest",
    "plan_payload_units",
    "read_bag_info",
    "read_manifest_sha256",
    "read_package_index",
    "receive_source",
    "safe_payload_path",
    "sha256_file",
    "slug_operator",
    "sweep_orphans",
    "tagmanifest_text",
    "validate_bag",
    "wait_for_server_confirmation",
    "write_bagit_files",
]
